### ISSUE TITLE
Setup not working on Neovim when installed with MacOS Homebrew

### ISSUE THREAD

**Issue by skossan** [wooshdude/leafvim#1]
When installing Nvim via MacOS Homebrew package manager it seems like the setup file will put the config files in the incorrect location. 

Anyway this could be fixed?

**Comment by skossan** [comment]
This is actually my bad. The _nvim_ folder was not created inside the _.config_ folder. It would be great if the script could create the folder if it doesn't already exist!

**Comment by wooshdude** [comment]
Good idea! I'll add that in the next update.
